# Generated by Django 4.1.13 on 2026-01-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0003_alter_tbl_company_status_alter_tbl_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ship',
            fields=[
                ('ship_id', models.AutoField(primary_key=True, serialize=False)),
                ('ship_name', models.CharField(max_length=100)),
                ('capacity_ton', models.IntegerField()),
                ('built_year', models.IntegerField()),
                ('image', models.ImageField(upload_to='ships/')),
                ('status', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_company')),
            ],
        ),
    ]
