# Generated by Django 4.1.13 on 2026-01-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAdmin', '0001_initial'),
        ('LCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company_ship_route',
            fields=[
                ('ship_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAdmin.tbl_routes')),
                ('ship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LCompany.tbl_ship')),
            ],
        ),
    ]
