# Generated by Django 4.1.13 on 2026-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCompany', '0002_tbl_company_ship_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company_ship_route',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
