# Generated by Django 4.1.13 on 2026-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCompany', '0003_alter_tbl_company_ship_route_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedbacks',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
