# Generated by Django 4.1.13 on 2026-01-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0003_alter_tbl_company_status_alter_tbl_user_status'),
        ('LAdmin', '0001_initial'),
        ('LCompany', '0003_alter_tbl_company_ship_route_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_transportation_request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('container_type', models.CharField(max_length=200)),
                ('weight_ton', models.FloatField()),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(default='NULL', max_length=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_company')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAdmin.tbl_routes')),
                ('ship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LCompany.tbl_ship')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_user')),
            ],
        ),
    ]
