# Generated by Django 4.1.13 on 2026-02-02 05:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LUser', '0002_alter_tbl_transportation_request_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LUser.tbl_transportation_request')),
            ],
        ),
    ]
