# Generated by Django 4.1.13 on 2026-02-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_tbl_company_status_alter_tbl_user_status'),
        ('LUser', '0003_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_user')),
            ],
        ),
    ]
