# Generated by Django 4.1.13 on 2026-02-16 05:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_tbl_company_status_alter_tbl_user_status'),
        ('LUser', '0004_tbl_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_address',
            name='type',
            field=models.CharField(choices=[('Home', 'Home Address'), ('Company', 'Company Address'), ('Other', 'Other')], default='Home', max_length=50),
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LUser.tbl_transportation_request')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_user')),
            ],
        ),
    ]
