# Generated by Django 4.1.13 on 2026-01-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=40)),
                ('owner_name', models.CharField(max_length=40)),
                ('licence', models.CharField(max_length=300)),
                ('id_proof', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_login')),
            ],
        ),
    ]
