# Generated by Django 4.1.13 on 2026-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_tbl_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
