# Generated by Django 4.1.13 on 2026-02-16 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_tbl_company_status_alter_tbl_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_forgot_password_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('otp', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
