# Generated by Django 4.1.13 on 2026-02-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_tbl_forgot_password_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_forgot_password_otp',
            new_name='tbl_otp',
        ),
    ]
