# Generated by Django 4.1.13 on 2026-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_port', models.EmailField(max_length=350)),
                ('arrival_port', models.CharField(max_length=358)),
            ],
        ),
    ]
